import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (

        <div className={styles.container}>
            <Head>
                <title>asiur</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.1/css/all.css' rel='stylesheet' type='text/css'/>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.9.4/dist/css/uikit.min.css" />

            </Head>
            <p className={styles.gta}>
                Get started to introducation{' '}
                <code className={styles.button}>ASIUR RAHAMAN</code>
            </p>


            <div className={styles.tds}>
                <h2 style={{color:"white"}}>introducation &rarr;</h2>
                <p style={{color:"white"}}>
                    Hi i am asiurrahaman
                    i am passing higher scendory education
                    actually im not diploma  qualification
                    but i  love coding on back end php and frontend recat js and dreaming in frontend devloper to build comliex web application servin reacet and modern technologies
                </p>
            </div>

            <main className={styles.main}>
                <h3 className={styles.title}>
                    <link rel="icon" href="/ivon.ico" /> <a href="https://www.facebook.com/asiur.rahaman"></a>

                    <i className='fab fa-facebook fa-3x' style={{color:'blue'}}></i>
                    <a>FACEBOOK</a>

                </h3>
            </main>
            <main>
                <div className={styles.follow}>
                    <a href="https://www.linkedin.com/in/asiur-rahaman-379066186/"></a>
                    <i className='fab fa-linkedin fa-4x fa-center' style={{color:"blue"}}></i>
                    <a>linkedin</a>
                </div>

                <div className={styles.main} style={{color:"white"}} >
                    <a href='https://www.youtube.com/channel/UCS5j83k4Q89lHORP8lh442w' >
                        <i className='fab fa-youtube fa-4x ' style={{color:'red'}}></i>
                        <h3 style={{color:"white"}}>YOUTUBE Content  &rarr; </h3>
                        <p>Hi frinde im youtuber and creating video for funny and infomation so please subscribe my channale</p>
                    </a>
                </div>
            </main>
            <main>
                <div className={styles.card} style={{color:"white"}}>
                    <a href='https://www.instagram.com/asiurrahaman/' >
                        <i className='fab fa-cc-apple-pay fa-4x' style={{color:'red'}}></i>
                        <h2 style={{color:"white"}}>FOLLOW </h2>
                        <p>follow my instagram id asiurrahaman</p>
                    </a>
                </div>

            </main>



            <main>
                <div>
                    <footer className={styles.footer}>
                        <a href="https://drive.google.com/file/d/13FQ--yQfHf_NOR4cVJZz88vy5Y8lLd0G/view?usp=sharing"

                        >
                            FOLLOW US{""}
                            <span className={styles.logo}>
                               <i className="fab fa-youtube fa-4x" style={{color:"red"}}></i>
                              <i className="fab fa-laptop">logi</i>
                                <i className="fab fa-google fa-4x"></i>
                                <i className='fab fa-apple fa-4x' style={{color:'silver'}}></i>
            <Image src="/vercel.svg" alt="vercel.icon" width={72} height={16} />
          </span>
                        </a>
                    </footer>
                </div>
            </main>
        </div>
    )
}
